apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: gcr.io/kuberenetesassignment/k8testimage-app1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: persistent-storage
              mountPath: /harshpreet_PV_dir
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: harshpreetpvc
